name: workflow a

on:
  check_suite:
    types: [completed]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: dump event
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT