name: workflow c

on:
  push:
    branches:
     - '**'

jobs:
  one-c:
    runs-on: ubuntu-latest
    steps:
      - name: wait
        uses: WyriHaximus/github-action-wait-for-status@0.1.0
        with:
          ignoreActions: one-c
          checkInterval: 10 # this is the default
      - name: dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT