name: workflow c

on:
  push:
    branches:
     - '**'

jobs:
  one-c:
    runs-on: ubuntu-latest
    steps:
      - name: wait
        uses: WyriHaximus/github-action-wait-for-status@v1.2.0
        with:
          ignoreActions: one-c
          checkInterval: 10 # this is the default
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  
      - name: dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo $GITHUB_CONTEXT